# Generated by Django 2.1.4 on 2018-12-07 14:08

import ckeditor_uploader.fields
from django.db import migrations
import read_statistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181206_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name=read_statistics.models.ReadDetail),
        ),
    ]
